DROP TABLE IF EXISTS health_data;
CREATE TABLE health_data (
    icu_patients INT,
    icu_patients_per_million FLOAT,
    hosp_patients INT,
    hosp_patients_per_million FLOAT,
    weekly_icu_admissions FLOAT,
    weekly_icu_admissions_per_million FLOAT,
    weekly_hosp_admissions FLOAT,
    weekly_hosp_admissions_per_million FLOAT,
    total_tests BIGINT,
    new_tests INT,
    total_tests_per_thousand FLOAT,
    new_tests_per_thousand FLOAT,
    new_tests_smoothed INT,
    new_tests_smoothed_per_thousand FLOAT,
    positive_rate FLOAT,
    tests_per_case FLOAT,
    tests_units VARCHAR(255),
    total_vaccinations BIGINT,
    people_vaccinated BIGINT,
    people_fully_vaccinated BIGINT,
    total_boosters BIGINT,
    new_vaccinations INT,
    new_vaccinations_smoothed INT,
    total_vaccinations_per_hundred FLOAT,
    people_vaccinated_per_hundred FLOAT,
    people_fully_vaccinated_per_hundred FLOAT,
    total_boosters_per_hundred FLOAT,
    new_vaccinations_smoothed_per_million INT,
    new_people_vaccinated_smoothed INT,
    new_people_vaccinated_smoothed_per_hundred FLOAT,
    stringency_index FLOAT,
    population_density FLOAT,
    median_age FLOAT,
    aged_65_older FLOAT,
    aged_70_older FLOAT,
    gdp_per_capita FLOAT,
    extreme_poverty FLOAT,
    cardiovasc_death_rate FLOAT,
    diabetes_prevalence FLOAT,
    female_smokers FLOAT,
    male_smokers FLOAT,
    handwashing_facilities FLOAT,
    hospital_beds_per_thousand FLOAT,
    life_expectancy FLOAT,
    human_development_index FLOAT,
    population BIGINT,
    excess_mortality_cumulative_absolute FLOAT,
    excess_mortality_cumulative FLOAT,
    excess_mortality FLOAT,
    excess_mortality_cumulative_per_million VARCHAR(50)
);
LOAD DATA INFILE 'C:/health_data.csv'
INTO TABLE health_data
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(
    @icu_patients,
    @icu_patients_per_million,
    @hosp_patients,
    @hosp_patients_per_million,
    @weekly_icu_admissions,
    @weekly_icu_admissions_per_million,
    @weekly_hosp_admissions,
    @weekly_hosp_admissions_per_million,
    @total_tests,
    @new_tests,
    @total_tests_per_thousand,
    @new_tests_per_thousand,
    @new_tests_smoothed,
    @new_tests_smoothed_per_thousand,
    @positive_rate,
    @tests_per_case,
    @tests_units,
    @total_vaccinations,
    @people_vaccinated,
    @people_fully_vaccinated,
    @total_boosters,
    @new_vaccinations,
    @new_vaccinations_smoothed,
    @total_vaccinations_per_hundred,
    @people_vaccinated_per_hundred,
    @people_fully_vaccinated_per_hundred,
    @total_boosters_per_hundred,
    @new_vaccinations_smoothed_per_million,
    @new_people_vaccinated_smoothed,
    @new_people_vaccinated_smoothed_per_hundred,
    @stringency_index,
    @population_density,
    @median_age,
    @aged_65_older,
    @aged_70_older,
    @gdp_per_capita,
    @extreme_poverty,
    @cardiovasc_death_rate,
    @diabetes_prevalence,
    @female_smokers,
    @male_smokers,
    @handwashing_facilities,
    @hospital_beds_per_thousand,
    @life_expectancy,
    @human_development_index,
    @population,
    @excess_mortality_cumulative_absolute,
    @excess_mortality_cumulative,
    @excess_mortality,
    @excess_mortality_cumulative_per_million
)
SET
    icu_patients = NULLIF(@icu_patients, ''),
    icu_patients_per_million = NULLIF(@icu_patients_per_million, ''),
    hosp_patients = NULLIF(@hosp_patients, ''),
    hosp_patients_per_million = NULLIF(@hosp_patients_per_million, ''),
    weekly_icu_admissions = NULLIF(@weekly_icu_admissions, ''),
    weekly_icu_admissions_per_million = NULLIF(@weekly_icu_admissions_per_million, ''),
    weekly_hosp_admissions = NULLIF(@weekly_hosp_admissions, ''),
    weekly_hosp_admissions_per_million = NULLIF(@weekly_hosp_admissions_per_million, ''),
    total_tests = NULLIF(@total_tests, ''),
    new_tests = NULLIF(@new_tests, ''),
    total_tests_per_thousand = NULLIF(@total_tests_per_thousand, ''),
    new_tests_per_thousand = NULLIF(@new_tests_per_thousand, ''),
    new_tests_smoothed = NULLIF(@new_tests_smoothed, ''),
    new_tests_smoothed_per_thousand = NULLIF(@new_tests_smoothed_per_thousand, ''),
    positive_rate = NULLIF(@positive_rate, ''),
    tests_per_case = NULLIF(@tests_per_case, ''),
    tests_units = NULLIF(@tests_units, ''),
    total_vaccinations = NULLIF(@total_vaccinations, ''),
    people_vaccinated = NULLIF(@people_vaccinated, ''),
    people_fully_vaccinated = NULLIF(@people_fully_vaccinated, ''),
    total_boosters = NULLIF(@total_boosters, ''),
    new_vaccinations = NULLIF(@new_vaccinations, ''),
    new_vaccinations_smoothed = NULLIF(@new_vaccinations_smoothed, ''),
    total_vaccinations_per_hundred = NULLIF(@total_vaccinations_per_hundred, ''),
    people_vaccinated_per_hundred = NULLIF(@people_vaccinated_per_hundred, ''),
    people_fully_vaccinated_per_hundred = NULLIF(@people_fully_vaccinated_per_hundred, ''),
    total_boosters_per_hundred = NULLIF(@total_boosters_per_hundred, ''),
    new_vaccinations_smoothed_per_million = NULLIF(@new_vaccinations_smoothed_per_million, ''),
    new_people_vaccinated_smoothed = NULLIF(@new_people_vaccinated_smoothed, ''),
    new_people_vaccinated_smoothed_per_hundred = NULLIF(@new_people_vaccinated_smoothed_per_hundred, ''),
    stringency_index = NULLIF(@stringency_index, ''),
    population_density = NULLIF(@population_density, ''),
    median_age = NULLIF(@median_age, ''),
    aged_65_older = NULLIF(@aged_65_older, ''),
    aged_70_older = NULLIF(@aged_70_older, ''),
    gdp_per_capita = NULLIF(@gdp_per_capita, ''),
    extreme_poverty = NULLIF(@extreme_poverty, ''),
    cardiovasc_death_rate = NULLIF(@cardiovasc_death_rate, ''),
    diabetes_prevalence = NULLIF(@diabetes_prevalence, ''),
    female_smokers = NULLIF(@female_smokers, ''),
    male_smokers = NULLIF(@male_smokers, ''),
    handwashing_facilities = NULLIF(@handwashing_facilities, ''),
    hospital_beds_per_thousand = NULLIF(@hospital_beds_per_thousand, ''),
    life_expectancy = NULLIF(@life_expectancy, ''),
    human_development_index = NULLIF(@human_development_index, ''),
    population = NULLIF(@population, ''),
    excess_mortality_cumulative_absolute = NULLIF(@excess_mortality_cumulative_absolute, ''),
    excess_mortality_cumulative = NULLIF(@excess_mortality_cumulative, ''),
    excess_mortality = NULLIF(@excess_mortality, ''),
    excess_mortality_cumulative_per_million = NULLIF(@excess_mortality_cumulative_per_million, '');
